site_name: ErlangBook
site_author: Arif Hussain Bangash
page:
  - Home: index.md
  - About: about.md

theme: 
  name: material
  custom_dir: 'material'
  palette:
    primary: 'red'
    accent: 'red'
  # logo:
  #   icon: opacity
  # favicon: 'assets/images/favicon.ico'

repo_name: 'Source at Github'
repo_url: 'https://github.com/erlangbook/source'
edit_uri: ''

extra:
  social:
    - type: 'github'
      link: 'https://github.com/erlangbook'
    - type: 'twitter'
      link: 'https://twitter.com/devotiongeo'

markdown_extensions:
  - codehilite
  - admonition
  - toc:
      permalink: true
